version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker:  circleci/docker@2.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install
  test:
    docker: 
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests"
          npm run test

  build-and-push:
    docker:
      - image:  circleci/docker:20.10.7
    steps:
      - checkout
      - setup_remote_docker
      - docker/login:
        username:  $DOCKER_USERNAME
        password:  $DOCKER_PASSWORD
      - docker/build:
        image:  bindugopinathan/education-space:latest 
      - docker/push:
        image:  bindugopinathan/education-space:latest  

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - build-and-push:
          requires:
            - test      